#!/usr/bin/env bash
# Generated by deploy/installer/build_bootstrap.py. Edit the template/shared verifier.
set -Eeuo pipefail
umask 077
absensa_bootstrap() {
    local install_dir answer temp_dir os_id os_version need_base package key_sum
    local -a elevate=() missing=()
    trap 'printf "\nInstalasi terhenti. Data yang sudah ada dipertahankan. Periksa pesan sebelumnya, lalu jalankan lagi.\n" >&2' ERR
    if [[ ${1:-} == --help ]]; then
        printf 'Pemasang Absensa: bash install.sh [direktori-instalasi]\nMemerlukan terminal, Linux amd64, dan koneksi HTTPS.\n'
        return
    fi
    [[ $(uname -s) == Linux && $(uname -m) == x86_64 ]] || { printf 'Gunakan Linux amd64. Windows: jalankan install.ps1; Windows Server: gunakan VM Ubuntu 24.04 LTS.\n' >&2; return 1; }
    [[ -r /dev/tty ]] || { printf 'Jalankan dari terminal interaktif.\n' >&2; return 1; }
    # os-release is local OS metadata, never a downloaded script.
    os_id=$(sed -n 's/^ID=//p' /etc/os-release | tr -d '"')
    os_version=$(sed -n 's/^VERSION_ID=//p' /etc/os-release | tr -d '"')
    case "$os_id:$os_version" in
        ubuntu:22.04|ubuntu:24.04|debian:12|debian:13) ;;
        *) printf 'Instalasi otomatis mendukung Ubuntu 22.04/24.04 LTS dan Debian 12/13 amd64. Gunakan VM Ubuntu 24.04 LTS untuk lingkungan lainnya.\n' >&2; return 1 ;;
    esac
    install_dir=${1:-${HOME}/absensa}
    printf 'Direktori instalasi [%s]: ' "$install_dir" > /dev/tty
    IFS= read -r answer < /dev/tty
    install_dir=${answer:-$install_dir}
    [[ $install_dir =~ ^/[a-zA-Z0-9_./-]+$ && $install_dir != *'/../'* ]] || { printf 'Gunakan direktori absolut tanpa spasi atau karakter khusus.\n' >&2; return 1; }
    if [[ -f $install_dir/state.json && -x $install_dir/absensa ]] && python3 -c 'import json,sys; from pathlib import Path; p=Path(sys.argv[1]); sys.exit(0 if (p/"releases"/json.loads((p/"state.json").read_text())["version"]/"manage.py").is_file() else 1)' "$install_dir"; then
        "$install_dir/absensa"
        return
    fi
    if [[ -d $install_dir && ! -f $install_dir/state.json ]] && [[ -n $(ls -A "$install_dir") ]]; then
        printf 'Direktori sudah berisi data. Jangan timpa instalasi lama; gunakan panduan pemulihan atau pilih direktori kosong.\n' >&2
        return 1
    fi
    for package in python3 curl openssl ca-certificates gnupg; do
        if ! dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -qx 'install ok installed'; then missing+=("$package"); fi
    done
    need_base=${#missing[@]}
    if (( need_base > 0 )) || ! command -v docker >/dev/null || ! command -v gh >/dev/null; then
        printf 'Dependensi yang belum ada akan dipasang melalui APT bertanda tangan. Repositori resmi Docker/GitHub CLI ditambahkan bila diperlukan. APT dapat memasang dependensi paket; layanan Docker baru dapat mengubah aturan jaringan Docker. Tidak ada reboot otomatis.\n'
        printf 'Izinkan pemasangan paket dan penggunaan hak administrator? (ya/tidak) [tidak]: ' > /dev/tty
        IFS= read -r answer < /dev/tty
        [[ $answer == ya ]] || { printf 'Dibatalkan. Pasang dependensi bersama petugas IT lalu jalankan kembali.\n'; return 1; }
        if (( EUID != 0 )); then
            command -v sudo >/dev/null || { printf 'Sudo tidak tersedia. Minta administrator menjalankan installer dari terminal root.\n'; return 1; }
            elevate=(sudo)
            # The invoking account deliberately opens its own terminal.
            # shellcheck disable=SC2024
            sudo -v < /dev/tty
        fi
        if (( need_base > 0 )); then
            "${elevate[@]}" apt-get update
            "${elevate[@]}" apt-get install --no-install-recommends --no-upgrade "${missing[@]}" < /dev/tty
        fi
    fi
    temp_dir=$(mktemp -d -t absensa-installer.XXXXXXXX)
    # Clean only the private directory created by this invocation.
    trap 'rm -rf -- "$temp_dir"' RETURN
    if ! command -v gh >/dev/null; then
        curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL --retry 3 --max-time 120 https://cli.github.com/packages/githubcli-archive-keyring.gpg -o "$temp_dir/gh.gpg"
        key_sum=$(sha256sum "$temp_dir/gh.gpg")
        [[ ${key_sum%% *} == 6084d5d7bd8e288441e0e94fc6275570895da18e6751f70f057485dc2d1a811b ]] || { printf 'Kunci APT GitHub berubah. Installer berhenti; pengelola harus meninjau pembaruan kunci resmi.\n'; return 1; }
        [[ ! -e /etc/apt/sources.list.d/absensa-gh.list && ! -e /etc/apt/keyrings/absensa-gh.gpg ]] || { printf 'Konfigurasi APT Absensa sudah ada tetapi gh tidak tersedia. Minta petugas IT memeriksa APT.\n'; return 1; }
        "${elevate[@]}" install -d -m 0755 /etc/apt/keyrings
        "${elevate[@]}" install -m 0644 "$temp_dir/gh.gpg" /etc/apt/keyrings/absensa-gh.gpg
        printf 'deb [arch=amd64 signed-by=/etc/apt/keyrings/absensa-gh.gpg] https://cli.github.com/packages stable main\n' > "$temp_dir/gh.list"
        "${elevate[@]}" install -m 0644 "$temp_dir/gh.list" /etc/apt/sources.list.d/absensa-gh.list
        "${elevate[@]}" apt-get update
        "${elevate[@]}" apt-get install --no-install-recommends --no-upgrade gh < /dev/tty
    fi
    gh attestation verify --help | grep -q -- '--source-ref' || { printf 'GitHub CLI terlalu lama. Minta petugas IT memperbarui gh melalui repositori resminya; installer tidak memperbarui perangkat lunak yang ada secara diam-diam.\n'; return 1; }
    if ! command -v docker >/dev/null; then
        for package in docker.io docker-ce docker-ce-cli containerd containerd.io runc podman-docker; do
            if dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -qx 'install ok installed'; then
                printf 'Paket container %s sudah ada. Installer tidak menggantinya. Minta petugas IT menyediakan Docker Engine dan Compose yang kompatibel.\n' "$package"
                return 1
            fi
        done
        [[ ! -e /etc/apt/sources.list.d/absensa-docker.list && ! -e /etc/apt/keyrings/absensa-docker.asc ]] || { printf 'Konfigurasi APT Docker sudah ada. Minta petugas IT menyelesaikan pemasangan Docker.\n'; return 1; }
        curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL --retry 3 --max-time 120 "https://download.docker.com/linux/$os_id/gpg" -o "$temp_dir/docker.asc"
        gpg --batch --show-keys --with-colons "$temp_dir/docker.asc" 2>/dev/null | grep -q '^fpr:::::::::9DC858229FC7DD38854AE2D88D81803C0EBFCD88:' || { printf 'Sidik jari kunci Docker tidak sesuai. Pemasangan dihentikan.\n'; return 1; }
        "${elevate[@]}" install -d -m 0755 /etc/apt/keyrings
        "${elevate[@]}" install -m 0644 "$temp_dir/docker.asc" /etc/apt/keyrings/absensa-docker.asc
        local codename
        codename=$(sed -n 's/^VERSION_CODENAME=//p' /etc/os-release | tr -d '"')
        [[ $codename =~ ^[a-z]+$ ]] || return 1
        printf 'deb [arch=amd64 signed-by=/etc/apt/keyrings/absensa-docker.asc] https://download.docker.com/linux/%s %s stable\n' "$os_id" "$codename" > "$temp_dir/docker.list"
        "${elevate[@]}" install -m 0644 "$temp_dir/docker.list" /etc/apt/sources.list.d/absensa-docker.list
        "${elevate[@]}" apt-get update
        "${elevate[@]}" apt-get install --no-install-recommends --no-upgrade docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin < /dev/tty
        if command -v systemctl >/dev/null && [[ -d /run/systemd/system ]]; then
            "${elevate[@]}" systemctl enable --now docker
        fi
    fi
    if ! docker info >/dev/null 2>&1; then
        printf 'Docker belum berjalan atau akun ini belum berhak menggunakannya. Minta petugas IT memeriksa layanan dan akses Docker. Setelah disetujui, jalankan kembali sebagai akun pengelola Docker atau root; installer tidak mengubah keanggotaan grup otomatis.\n' >&2
        return 1
    fi
    printf 'Mencari rilis stabil dan memverifikasi asal artefak…\n'
    python3 - "$temp_dir" "$install_dir" <<'PYBOOT'
"""Trust boundary shared by the bootstrap and installed manager (stdlib only)."""

import hashlib
import json
import re
import subprocess
import tarfile
import urllib.error
import urllib.request
from pathlib import Path

REPOSITORY = "u70i1/absensa"
TAG = re.compile(r"v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\Z")
ARTIFACT = "absensa-linux-amd64.tar.gz"
MAX_DOWNLOAD = 32 * 1024 * 1024


class InstallError(Exception):
    pass


def download(url, destination, limit=MAX_DOWNLOAD):
    if not url.startswith("https://"):
        raise InstallError("Unduhan wajib menggunakan HTTPS.")
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Absensa-installer",
            "Accept": "application/vnd.github+json",
        },
    )
    try:
        with (
            urllib.request.urlopen(request, timeout=60) as response,
            open(destination, "xb") as output,
        ):
            if not response.url.startswith("https://"):
                raise InstallError("Pengalihan unduhan tidak aman.")
            size = 0
            while data := response.read(1024 * 1024):
                size += len(data)
                if size > limit:
                    raise InstallError("Ukuran unduhan melampaui batas.")
                output.write(data)
    except (OSError, urllib.error.URLError) as exc:
        raise InstallError(
            "Unduhan gagal. Periksa internet, tanggal server, batas API GitHub, dan ketersediaan rilis stabil."
        ) from exc


def latest(directory):
    destination = Path(directory) / "latest.json"
    download(
        f"https://api.github.com/repos/{REPOSITORY}/releases/latest",
        destination,
        1024 * 1024,
    )
    release = json.loads(destination.read_text())
    tag = release.get("tag_name", "")
    if (
        release.get("draft", True)
        or release.get("prerelease", True)
        or not TAG.fullmatch(tag)
    ):
        raise InstallError("Rilis stabil dengan tag vMAJOR.MINOR.PATCH belum tersedia.")
    names = {asset["name"] for asset in release.get("assets", [])}
    if not {ARTIFACT, "SHA256SUMS", "provenance.jsonl"} <= names:
        raise InstallError(
            "Rilis belum lengkap. Pengelola perlu menerbitkan artefak dan bukti asal rilis."
        )
    return tag


def extract(archive, destination):
    """Reject links, devices, duplicates, traversal and decompression bombs."""
    destination = Path(destination)
    with tarfile.open(archive, "r:gz") as source:
        members = source.getmembers()
        names = set()
        size = 0
        for member in members:
            path = Path(member.name)
            if (
                path.is_absolute()
                or ".." in path.parts
                or not path.parts
                or member.name in names
                or not (member.isfile() or member.isdir())
            ):
                raise InstallError("Arsip rilis tidak aman.")
            names.add(member.name)
            size += member.size
            if size > MAX_DOWNLOAD or len(names) > 300:
                raise InstallError("Isi arsip rilis terlalu besar.")
        for member in members:
            target = destination / member.name
            if member.isdir():
                target.mkdir(parents=True, exist_ok=True, mode=0o700)
            else:
                target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
                with source.extractfile(member) as stream, target.open("xb") as output:
                    output.write(stream.read())
                target.chmod(0o600)


def fetch(directory, tag=None):
    directory = Path(directory)
    tag = tag or latest(directory)
    if not TAG.fullmatch(tag):
        raise InstallError("Tag rilis tidak sah.")
    base = f"https://github.com/{REPOSITORY}/releases/download/{tag}"
    for name in (ARTIFACT, "SHA256SUMS", "provenance.jsonl"):
        download(f"{base}/{name}", directory / name)
    archive = directory / ARTIFACT
    expected = (directory / "SHA256SUMS").read_text().strip().split()
    if (
        len(expected) != 2
        or expected[1] != ARTIFACT
        or expected[0] != hashlib.sha256(archive.read_bytes()).hexdigest()
    ):
        raise InstallError(
            "Checksum rilis tidak cocok. Tidak ada kode unduhan yang dijalankan."
        )
    # The bundle is untrusted input; gh verifies Fulcio/Rekor and exact workflow/tag.
    result = subprocess.run(
        [
            "gh",
            "attestation",
            "verify",
            str(archive),
            "--bundle",
            str(directory / "provenance.jsonl"),
            "--repo",
            REPOSITORY,
            "--hostname",
            "github.com",
            "--cert-identity",
            f"https://github.com/{REPOSITORY}/.github/workflows/release.yml@refs/tags/{tag}",
            "--source-ref",
            f"refs/tags/{tag}",
            "--deny-self-hosted-runners",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode:
        raise InstallError(
            "Bukti asal rilis tidak lolos verifikasi GitHub/Sigstore. Periksa versi gh, koneksi dan jam server; jangan lewati pemeriksaan ini."
        )
    destination = directory / "release"
    destination.mkdir(mode=0o700)
    extract(archive, destination)
    manifest = json.loads((destination / "release.json").read_text())
    if (
        manifest.get("version") != tag
        or manifest.get("format") != 1
        or manifest.get("architecture") != "amd64"
    ):
        raise InstallError("Manifest rilis tidak cocok dengan versi yang diminta.")
    for name in ("web", "backup", "whatsapp", "caddy", "postgres"):
        image = manifest.get("images", {}).get(name, "")
        if not re.fullmatch(r"[a-z0-9./_-]+@sha256:[0-9a-f]{64}", image):
            raise InstallError(
                "Rilis harus mengunci semua image dengan digest SHA-256."
            )
    return destination

import sys
try:
    source = fetch(Path(sys.argv[1]))
    result = subprocess.run([sys.executable, str(source / "manage.py"), "--directory", sys.argv[2], "--release", str(source)], stdin=open("/dev/tty"))
    raise SystemExit(result.returncode)
except Exception:  # Metadata/verification failures must not expose a traceback.
    print("Instalasi dihentikan: rilis stabil tidak tersedia atau verifikasi unduhan gagal. Periksa internet, jam server, versi gh, dan kelengkapan rilis di https://github.com/u70i1/absensa/releases. Tidak ada kode rilis yang belum terverifikasi dijalankan.", file=sys.stderr)
    raise SystemExit(1) from None
PYBOOT
}
absensa_bootstrap "$@"
