"""Add trusted devices and operator authentication

Revision ID: 0fbaf2d5ad9a
Revises: d943e2f671ab
Create Date: 2026-09-23 07:30:16.986111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbaf2d5ad9a'
down_revision: Union[str, Sequence[str], None] = 'd943e2f671ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trusted_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('binding_hash', sa.String(length=64), nullable=True),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pin_failures', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pin_failures >= 0 AND pin_failures <= 5', name='ck_device_pin_failures'),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('binding_hash')
    )
    op.create_index(op.f('ix_trusted_devices_username'), 'trusted_devices', ['username'], unique=True)
    op.create_table('operator_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('binding_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['trusted_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash'),
    sa.UniqueConstraint('device_id')
    )
    op.create_index(op.f('ix_operator_sessions_operator_id'), 'operator_sessions', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_sessions_operator_id'), table_name='operator_sessions')
    op.drop_table('operator_sessions')
    op.drop_index(op.f('ix_trusted_devices_username'), table_name='trusted_devices')
    op.drop_table('trusted_devices')
    op.drop_table('operators')
    # ### end Alembic commands ###
