"""Add Class table

Revision ID: 15fb4ca52391
Revises: 23f7f1c9f8b8
Create Date: 2026-08-08 08:38:09.243328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15fb4ca52391'
down_revision: Union[str, Sequence[str], None] = '23f7f1c9f8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=10), nullable=False, unique=True),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.add_column('students', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key("students_classes_id_fkey", 'students', 'classes', ['class_id'], ['class_id'], ondelete='SET NULL')
    op.drop_column('students', 'class')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('class', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint("students_classes_id_fkey", 'students', type_='foreignkey')
    op.drop_column('students', 'class_id')
    op.drop_table('classes')
    # ### end Alembic commands ###
