"""Add ON UPDATE CASCADE to ScanLog.student

Revision ID: 23f7f1c9f8b8
Revises: 2c202dc85fef
Create Date: 2026-08-07 08:05:10.520951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f7f1c9f8b8'
down_revision: Union[str, Sequence[str], None] = '2c202dc85fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scan_logs_student_nisn_fkey'), 'scan_logs', type_='foreignkey')
    op.create_foreign_key('scan_logs_student_nisn_fkey', 'scan_logs', 'students', ['student_nisn'], ['nisn'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scan_logs_student_nisn_fkey', 'scan_logs', type_='foreignkey')
    op.create_foreign_key(op.f('scan_logs_student_nisn_fkey'), 'scan_logs', 'students', ['student_nisn'], ['nisn'], ondelete='CASCADE')
    # ### end Alembic commands ###
