"""Add ON DELETE CASCADE to ScanLog.student

Revision ID: 2c202dc85fef
Revises: 4d10654811ee
Create Date: 2026-08-06 10:35:09.759302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c202dc85fef'
down_revision: Union[str, Sequence[str], None] = '4d10654811ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scan_logs_student_nisn_fkey'), 'scan_logs', type_='foreignkey')
    op.create_foreign_key('scan_logs_student_nisn_fkey', 'scan_logs', 'students', ['student_nisn'], ['nisn'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scan_logs_student_nisn_fkey', 'scan_logs', type_='foreignkey')
    op.create_foreign_key(op.f('scan_logs_student_nisn_fkey'), 'scan_logs', 'students', ['student_nisn'], ['nisn'])
    # ### end Alembic commands ###
