"""Alter scan_logs column: student_id -> student_nisn

Revision ID: 4d10654811ee
Revises: 2a244b363886
Create Date: 2026-08-03 08:31:48.015132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d10654811ee'
down_revision: Union[str, Sequence[str], None] = '2a244b363886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_logs', sa.Column('student_nisn', sa.String(length=10), nullable=False))
    op.drop_constraint(op.f('scan_logs_student_id_fkey'), 'scan_logs', type_='foreignkey')
    op.create_foreign_key("scan_logs_student_nisn_fkey", 'scan_logs', 'students', ['student_nisn'], ['nisn'])
    op.drop_column('scan_logs', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_logs', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint("scan_logs_student_nisn_fkey", 'scan_logs', type_='foreignkey')
    op.create_foreign_key(op.f('scan_logs_student_id_fkey'), 'scan_logs', 'students', ['student_id'], ['id'])
    op.drop_column('scan_logs', 'student_nisn')
    # ### end Alembic commands ###
