"""Change scan_logs FK to student_id

Revision ID: 4d9d8952afdd
Revises: 31aa33fd57b3
Create Date: 2026-08-17 09:23:48.327048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9d8952afdd'
down_revision: Union[str, Sequence[str], None] = '31aa33fd57b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_logs', sa.Column('student_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('scan_logs_student_nisn_fkey'), 'scan_logs', type_='foreignkey')
    op.create_foreign_key("scan_logs_student_id_fkey", 'scan_logs', 'students', ['student_id'], ['id'], ondelete='SET NULL')
    op.drop_column('scan_logs', 'student_nisn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_logs', sa.Column('student_nisn', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint("scan_logs_student_id_fkey", 'scan_logs', type_='foreignkey')
    op.create_foreign_key(op.f('scan_logs_student_nisn_fkey'), 'scan_logs', 'students', ['student_nisn'], ['nisn'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('scan_logs', 'student_id')
    # ### end Alembic commands ###
