"""class_name max length to 20

Revision ID: 7338de74587e
Revises: 7f3432ecae81
Create Date: 2026-09-10 09:06:20.519689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7338de74587e'
down_revision: Union[str, Sequence[str], None] = '7f3432ecae81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'class_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_comment='Short, unique name identifying the student group',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'class_name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_comment='Short, unique name identifying the student group',
               existing_nullable=False)
    # ### end Alembic commands ###
