"""Add grade

Revision ID: 7f3432ecae81
Revises: 9dbea3a654b4
Create Date: 2026-09-10 07:54:46.679558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3432ecae81'
down_revision: Union[str, Sequence[str], None] = '9dbea3a654b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('grade', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('classes_class_name_key'), 'classes', type_='unique')
    op.create_unique_constraint('uq_grade_class_name', 'classes', ['grade', 'class_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_grade_class_name', 'classes', type_='unique')
    op.create_unique_constraint(op.f('classes_class_name_key'), 'classes', ['class_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('classes', 'grade')
    # ### end Alembic commands ###
