"""Comments for columns

Revision ID: 9dbea3a654b4
Revises: d51c556adc6e
Create Date: 2026-08-19 15:39:57.685134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dbea3a654b4'
down_revision: Union[str, Sequence[str], None] = 'd51c556adc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'class_name',
               existing_type=sa.VARCHAR(length=10),
               comment='Short, unique name identifying the student group',
               existing_nullable=False)
    op.alter_column('scan_logs', 'student_id',
               existing_type=sa.INTEGER(),
               comment='Foreign key to the "students" table. Set to `NULL` if the corresponding student is deleted.',
               existing_nullable=True)
    op.alter_column('scan_logs', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment="Student's name at the time of the scan.",
               existing_nullable=False)
    op.alter_column('scan_logs', 'class',
               existing_type=sa.VARCHAR(length=10),
               comment="Student's class at the time of the scan.",
               existing_nullable=True)
    op.alter_column('scan_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Time when the scan was recorded, with timezone information.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('students', 'nisn',
               existing_type=sa.VARCHAR(length=10),
               comment='National student ID number (Indonesia). Always exactly 10 digits. Deferrable. Initially immediate',
               existing_nullable=False)
    op.alter_column('students', 'current',
               existing_type=sa.BOOLEAN(),
               comment='Indicate if a student is still in school or not',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'current',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indicate if a student is still in school or not',
               existing_nullable=False)
    op.alter_column('students', 'nisn',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='National student ID number (Indonesia). Always exactly 10 digits. Deferrable. Initially immediate',
               existing_nullable=False)
    op.alter_column('scan_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Time when the scan was recorded, with timezone information.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scan_logs', 'class',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment="Student's class at the time of the scan.",
               existing_nullable=True)
    op.alter_column('scan_logs', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Student's name at the time of the scan.",
               existing_nullable=False)
    op.alter_column('scan_logs', 'student_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Foreign key to the "students" table. Set to `NULL` if the corresponding student is deleted.',
               existing_nullable=True)
    op.alter_column('classes', 'class_name',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Short, unique name identifying the student group',
               existing_nullable=False)
    # ### end Alembic commands ###
