"""Make NISN unique key constraint deferrable

Revision ID: d51c556adc6e
Revises: 4d9d8952afdd
Create Date: 2026-08-17 10:40:54.069995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51c556adc6e'
down_revision: Union[str, Sequence[str], None] = '4d9d8952afdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("students_nisn_key", "students", type_="unique")
    op.create_unique_constraint(
        "students_nisn_key", "students", ["nisn"], deferrable=True, initially="IMMEDIATE"
    )
    op.drop_constraint("classes_class_name_key", "classes", type_="unique")
    op.create_unique_constraint(
        "classes_class_name_key", "classes", ["class_name"], deferrable=True, initially="IMMEDIATE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint("students_nisn_key", "students", type_="unique")
    op.create_unique_constraint("students_nisn_key", "students", ["nisn"])
    op.drop_constraint("classes_class_name_key", "classes", type_="unique")
    op.create_unique_constraint("classes_class_name_key", "classes", ["class_name"])

    # ### end Alembic commands ###
